### ISSUE TITLE
Happy Feet (USA) - Flickering corrupt graphics

### ISSUE THREAD

**Issue by xTibor** [michelhe/rustboyadvance-ng#111]
They are not happy at the moment:
![vlcsnap-2020-05-30-13h23m01s729](https://user-images.githubusercontent.com/1627292/83327027-1bd66780-a279-11ea-95f2-d5101bc56266.png)

**Comment by michelhe** [comment]
Hope it's just another PPU state machine bug, or else I'm not gonna be happy either :cry:

**Comment by michelhe** [comment]
I'm beginning to worry that both this issue and #112  are related to cycle accuracy.. 
playing around with REG_WAITCNT (which effectively changes waitstates) is causing different kinds of graphical glitches to appear.

Maybe these games spend too much time in VBLANK, so when they v-sync the emulator is already out of vblank?

**Comment by michelhe** [comment]
![image](https://user-images.githubusercontent.com/2903914/83338725-caa59280-a2cf-11ea-866a-a7b7a7d33204.png)

Playing around with the cycle counting wrappers (in this example I'm arbitrarily adding 2 cycles for each type of access)  and voila, the warning screen now appears (instead of the black screen).
![image](https://user-images.githubusercontent.com/2903914/83338766-12c4b500-a2d0-11ea-9455-f060deb27959.png)

**Comment by michelhe** [comment]
And although the menu text flickers, the in-game scenes are not corrupted.

![image](https://user-images.githubusercontent.com/2903914/83338784-3daf0900-a2d0-11ea-9de7-359383afafa5.png)

**Comment by michelhe** [comment]
@xTibor It took *some* months but I figured out the issue 😩

The underlying problem is that these game (this and drake&josh as seen in #112 ) are using an IRQ triggering timer that is configured to increment every 1-cycle (16MHZ), and I'm updating the timers only after I've fast-forwarded the CPU to the next "event" (sound sample or GPU event), as seen here:
https://github.com/michelhe/rustboyadvance-ng/blob/master/core/src/gba.rs#L263

So when Timers::update, this timer will only raise an IRQ once even though it should have raised that IRQ for 'cycle' amounts of time.

Moving the Timer::update to line 254 like so:

```rust
 let _cycles = if !io.dmac.is_active() {
                if HaltState::Running == io.haltcnt {
                    self.step_cpu(io)
                } else {
                    cycles = cycles_left;
                    break;
                }
            } else {
                io.dmac.perform_work(&mut self.sysbus);
                return cycles;
            };
            io.timers.update(_cycles, &mut self.sysbus);
            cycles += _cycles;
```

Actually fixes these games but this brings a performance hit/

**Comment by michelhe** [comment]
Fixed in the recent scheduler changes
