### ISSUE TITLE
Android application

### ISSUE THREAD

**Issue by narakai** [michelhe/rustboyadvance-ng#167]
Thanks for the great work! 
Can you update instructions for how to build it with Android Studio, or is there an existing APK for Android? Just want to try it on my phone : )

**Comment by michelhe** [comment]
Hey @narakai , thank you very much for taking an interest in my project :)

I haven't built the android app for a while since I use iOS now, but I can build it for you after I'm back from our honeymoon in 3 weeks :P

If you have Android Studio and rust set up, then the existing android studio project inside this repo _should_ work, you just need to tweak some rustc configuration to point the linker to the arm toolchains included with Android Studio SDK.
[This guide](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html) looks like a good direction.

**Comment by narakai** [comment]
Hi Michelhe, thank you for your reply and enjoy your honeymoon!  I am familiar with Android but new to rust, I will try to build it myself first :)

**Comment by michelhe** [comment]
Hey @narakai , have you had any success ?

**Comment by narakai** [comment]
@michelhe tried but with no luck...

**Comment by michelhe** [comment]
@narakai  Hey, I reinstalled my android studio and built it, works on the emulator, if its still relevant you may try this one :) https://github.com/michelhe/rustboyadvance-ng/releases/tag/test-build

**Comment by narakai** [comment]
Thanks! I'll have a try on my phone.

**Comment by john-peterson** [comment]
debug apk : not compatible with your phone 
Release apk: package invalid
