### ISSUE TITLE
Incorrect affine transformations in Wario Land 4

### ISSUE THREAD

**Issue by xTibor** [michelhe/rustboyadvance-ng#79]
Upon entering a new stage in Wario Land 4 there's an animation of a rotating vortex. It should be rotating at the dead center of the screen, however RustBoyAdvance-NG currently renders it off-center. The rotation also glitches twice during the animation.

**Screenshot:**

![](https://user-images.githubusercontent.com/1627292/81441254-bc9d9f80-9171-11ea-99c0-7fc2a55c41cd.png)

**Expected rendering (mGBA master)**:

![](https://user-images.githubusercontent.com/1627292/81441265-c1625380-9171-11ea-96ef-f72fbb96dcf4.png)

**Comment by xTibor** [comment]
This off-center rotation is also reproducible with the `sbb_aff.gba` TONC demo (L+R keys) but not as severe as the Wario one.

**Comment by michelhe** [comment]
@xTibor  Good catch, I'll look into it.

**Comment by michelhe** [comment]
I suspect that I'm not updating the BGX/BGY reference points in the right phase of the PPU state machine.

https://github.com/michelhe/rustboyadvance-ng/blob/master/rustboyadvance-core/src/gpu/mod.rs#L400

**Comment by michelhe** [comment]
@xTibor 

https://github.com/michelhe/rustboyadvance-ng/blob/master/rustboyadvance-core/src/iodev.rs#L154

Removing these if-checks for all BG2-3X-Y registers solves this glitch (tested for Wario and `sbb_aff.gba`)

I've included this check because of the following line in GBATek:

> Caution: Writing to a reference point register by software outside of the Vblank period does immediately copy the new value to the corresponding internal register, that means: in the current frame, the new value specifies the origin of the <current> scanline (instead of the topmost scanline).

http://problemkaputt.de/gbatek.htm#lcdiobgrotationscaling

Too tired to continue now, but probably will sort it out tomorrow, might have interpreted this edge-case incorrectly.

**Comment by michelhe** [comment]
![image](https://user-images.githubusercontent.com/2903914/81468736-075afe00-91ea-11ea-8745-59c741e075ca.png)

Mode7 is broken when removing these `if`s
